echo: ok lah

database:
  driverClass: org.apache.derby.jdbc.EmbeddedDriver
  user: symbiotUser
  password: $ymb10t~dB-p@s$w0rd
  url: jdbc:derby:symbiotDB
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ values 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute